remove checkout unused env vars
pagopa/pagopa-ecommerce-fe pull request #16
Opened 2024-01-09 10:37 UTC by ciuffagianluca

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-01-09 13:34 UTC, pietro-tota commented on src/utils/config/config.ts
> -  CHECKOUT_PAGOPA_APIM_HOST: NonEmptyString,
remove those parameters also from  [azure-templates/setup-env.yml](https://github.com/pagopa/pagopa-ecommerce-fe/blob/d3f08e7af0ad295179dd5200835defefae3b3624/.devops/pagopa-deploy-pipelines.yml#L77C22-L77C52) template and deployment pipeline

2024-01-09 13:35 UTC, pietro-tota requested changes
Please remove those parameters also from deployment pipeline and template

2024-01-09 13:48 UTC, ciuffagianluca commented on src/utils/config/config.ts
> -  CHECKOUT_PAGOPA_APIM_HOST: NonEmptyString,
Addresed in a93af19327c04e90c4311d19fe90bb2b8699c8cd

2024-01-10 08:33 UTC, infantesimone approved these changes

2024-01-10 08:35 UTC, merged